# Numpy

## Diferencias entre listas y arrays
Una lista se parece a un arreglo pero funciona como una estructura de datos genérica.

En cambio, un array en numpy permite hacer operaciones matemáticas de manera más sencilla. 

In [2]:
import numpy as np


In [33]:
#Lista
L = [1,2,3]

for i in L:
    print(i)

1
2
3


In [34]:
#Array
A = np.array([1,2,3])

for i in A:
    print(i)

1
2
3


No existe el método append() en numpy. Los array, a diferencia de las listas en python, no pueden modificar su longitud.



In [8]:
L.append(4)
print(L)

[1, 2, 3, 4, 4, 4]


In [11]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

Para listas con la suma se incrementa la longitud y se agrega uno o varios elementos al final. Para arrays se produce la suma de cada elemento original con el nuevo y la longitud se mantiene.

Lo mismo sucede con la multiplicación


In [12]:
L + [5]

[1, 2, 3, 4, 4, 4, 5]

In [13]:
A + np.array([4])

array([5, 6, 7])

In [14]:
2*A

array([2, 4, 6])

In [15]:
2*L

[1, 2, 3, 4, 4, 4, 1, 2, 3, 4, 4, 4]

In [16]:
L2 = []
for i in L:
    L2.append(i+3)

L2

[4, 5, 6, 7, 7, 7]

In [20]:
L2 = [i+3 for i in L]
L2

[4, 5, 6, 7, 7, 7]

In [22]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [23]:
L2 = []
for i in L:
    L2.append(i**2)
L2

[1, 4, 9, 16, 16, 16]

In [24]:
A**2

array([1, 4, 9], dtype=int32)

In [29]:
np.sqrt(A)


array([0.76159416, 0.96402758, 0.99505475])

In [30]:
np.log(A)


array([0.        , 0.69314718, 1.09861229])

In [31]:
np.exp(A)



array([ 2.71828183,  7.3890561 , 20.08553692])

In [32]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## Producto punto

### Bucle for
Existen diferentes maneras de obtener el mismo resultado.
Puede realizarse la operación matemática mediante un bucle for donde se realice la operación a cada elemento durante las iteraciones, ya sea aplicando un función existente (primer caso) o utilizando la indexación de los elementos (segundo caso). 

### Numpy
Un método más óptimo para realizar lo mismo se consigue al utilizar la operación producto en numpy. Como la librería realiza la multiplicación elemento a elemento debemos añadir también la operación de suma para obtener el resultado esperado.

Incluso para lograrlo con mayor facilidad podemos usar la función dot() de numpy que proporciona el producto punto en un único paso.

In [35]:
a = np.array([1,2])
b = np.array([3,4])

In [36]:
dot = 0
for i, f in zip(a,b):
    dot += i * f
dot

11

In [37]:
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [38]:
a * b

array([3, 8])

In [39]:
np.sum(a * b)

11

In [40]:
(a * b).sum()

11

In [41]:
np.dot(a,b)

11

In [42]:
a.dot(b)

11

In [43]:
b.dot(a)

11

In [44]:
a @ b

11

## Matrices
 Una matriz es un array 2D
 
 Se muestran a continuación algunas de las operaciones que pueden hacerse con matrices en numpy

In [63]:
#Declaración de una lista de listas una matriz sin usar numpy
L = [[1,2] , [3,4]]
L

[[1, 2], [3, 4]]

In [49]:
#Declaración de un array para generar una matriz en numpy
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [50]:
#Dimensión
A.shape

(2, 2)

In [53]:
#Obtener todas las filas de la columna 0
A[:,0]

array([1, 3])

In [64]:
#Obtener todas las columnas de la fila 0
A[0,:]

array([1, 2])

In [55]:
#Traspuestaa
A.T

array([[1, 3],
       [2, 4]])

In [58]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [60]:
#Determinante
np.linalg.det(A)

-2.0000000000000004

In [61]:
#Inversa
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [62]:
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

## Resolución de sistemas lineales


In [65]:
A = np.array([[1,1] , [1.5,4]])
B = np.array([2200,5050])

np.linalg.solve(A,B)

array([1500.,  700.])

In [66]:
#No usar esta línea de código normalmente porque es más 
# lento, requiere mayor procesamiento y puede traer 
# problemas en casos con gran cantidad de datos

np.linalg.inv(A).dot(B)

array([1500.,  700.])

## Generación de datos

In [4]:
#generar valores ordenados con arange()
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [5]:
arr = np.arange(2, 10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.arange(2, 10, 2) #principio, fin, paso
arr

array([2, 4, 6, 8])

In [9]:
#array de 50 elementos con valores entre 5 y 8
np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [8]:
#array 1D de ceros
np.zeros(3)

array([0., 0., 0.])

In [69]:
#Array de ceros
np.zeros((2,3))



array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#matriz 2D de ceros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
#Array 2D de unos
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
25 * np.ones((2,3))

array([[25., 25., 25.],
       [25., 25., 25.]])

In [71]:
#Matriz identidad es 2D
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
#Arrays aleatorios
np.random.random()*10

array([6.87243293, 6.94222923])

In [73]:
np.random.random((2,3))

array([[0.50621331, 0.02260952, 0.53280801],
       [0.55523914, 0.8995891 , 0.42747745]])

In [75]:
#Generar n° aleatorios con distribución gaussiana 
# con media cero y varianza 1
np.random.randn(2,3)

array([[-0.13828998, -1.03226673,  1.09802509],
       [ 0.43678468, -0.05758891,  0.0520311 ]])

In [83]:
#Array de 10000 x 3 aleatorios con dist normal (gaussiana)
R = np.random.randn(10000,3)
R.mean() # o np.mean(R)

0.009702171436305295

In [84]:
R.var() #o np.var(R)

0.9991819651806235

In [85]:
#Raiz cuadrada de la varianza (desvio estandar)
R.std()

0.9995908989084602

In [86]:
#Promedio de cada columna
R.mean(axis=0)

array([0.00629811, 0.00468929, 0.01811912])

In [87]:
#Promedio de cada fila
R.mean(axis=1)

array([-0.57458309,  1.13819551,  0.73784486, ..., -0.31765669,
        1.10500855, -0.02282922])

In [88]:
R.mean(axis=1).shape

(10000,)

In [90]:
#Array de 3x3 con numeros aleatorios enteros entre 0 y 10
np.random.randint(0, 10, size=(3,3))

array([[9, 9, 4],
       [1, 8, 7],
       [3, 6, 5]])

In [10]:
np.random.randint(0, 10)

9

In [11]:
np.random.randint(0, 10, 3)

array([5, 1, 0])

## Operaciones con np.array()

### Redimensionar

In [14]:
arr = np.random.randint(1,100,25)
arr

array([92, 43, 21, 88, 27, 43, 94, 90,  9, 67,  2, 47, 83, 83,  2, 62, 83,
       96, 50, 13, 27, 99, 87, 79, 10])

In [13]:
mat = arr.reshape(5,5)  #los argumentos multip deben dar la cant del array 5x5=25
mat

array([[38, 64, 22, 72, 11],
       [79, 50,  3, 46, 25],
       [37, 33, 78, 10, 98],
       [85, 66, 37,  4, 70],
       [16, 76, 27, 12, 39]])

### Búsqueda de máximos y mínimos

In [20]:
#Máximo
mxm = arr.max()
mxm

99

In [18]:
#posición de máximo
mxm_p = arr.argmax()
mxm_p

21

In [25]:
#Mínimo
mnm = arr.min() #o np.min(array)
mnm

2

In [26]:
#posición del mínimo
mnm_p = arr.argmin()
mnm_p

10

## Indexación

Acceder a elementos específicos del array de diferentes formas y sectores


In [27]:
#Acceder a un elemento específico
arr[0]

92

In [28]:
arr[1]

43

In [29]:
#Elemento específico contando desde el final
arr[-1]

10

In [30]:
arr[-3]

87

In [31]:
#Del 2 en adelante
arr[2:]

array([21, 88, 27, 43, 94, 90,  9, 67,  2, 47, 83, 83,  2, 62, 83, 96, 50,
       13, 27, 99, 87, 79, 10])

In [32]:
#Desde el principio hasta el 3
arr[:3]

array([92, 43, 21])

In [35]:
#Del 2 al 6
arr[2:6]

array([21, 88, 27, 43])

In [36]:
#Completo
arr[:]

array([92, 43, 21, 88, 27, 43, 94, 90,  9, 67,  2, 47, 83, 83,  2, 62, 83,
       96, 50, 13, 27, 99, 87, 79, 10])

In [38]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [39]:
#Acceder a una fila específica
mat[0]

array([1, 2, 3])

In [40]:
#De la fila inicial a la 2
mat[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
#Acceder a un elemento específico
mat[0][1] # o mat[0,1]

2

In [42]:
#acceder a columnas
mat[:,0] #todas las filas de la columna 0

array([1, 4, 7])

In [43]:
mat[:,2]

array([3, 6, 9])

In [45]:
mat[:,:2] #Todas las filas. Columnas desde la primera hasta la 2

array([[1, 2],
       [4, 5],
       [7, 8]])

## Selección de elementos según una condición

In [67]:
array = np.random.randint(0, 10, 10)
array

array([2, 8, 8, 5, 3, 6, 3, 5, 9, 4])

In [68]:
condicion = array>5
condicion

array([False,  True,  True, False, False,  True, False, False,  True,
       False])

In [69]:
#ver cuales elementos cumplen la condicion
array[condicion]

array([8, 8, 6, 9])

In [70]:
arr = array[array<2]
arr

array([], dtype=int32)

In [71]:
array[array%2==0]

array([2, 8, 8, 6, 4])